<a href="https://colab.research.google.com/github/carlitos9087/Caderno_de_anotacoes_python/blob/main/SRR_files-graficos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install seaborn==0.12.0
import seaborn
seaborn.__version__

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting seaborn==0.12.0
  Downloading seaborn-0.12.0-py3-none-any.whl (285 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.1/285.1 KB 23.2 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.8/dist-packages (from seaborn==0.12.0) (3.2.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from seaborn==0.12.0) (1.21.6)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.8/dist-packages (from seaborn==0.12.0) (1.3.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.1->seaborn==0.12.0) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.1->seaborn==0.12.0) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.1->seaborn==0.12.0) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.1->seaborn==0.12.0) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.25->seaborn==0.12.0) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.1->matplotlib>=3.1->seaborn==0.12.0) (1.15.0)
Installing collected packages: seaborn
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
Successfully installed seaborn-0.12.0

'0.12.0'

In [ ]:
dados='/content/drive/MyDrive/Laboratory/Alunos/Carlos/SRR files/Leishmania/GSE162760'#local da pasta
tabela_final = '/content/drive/MyDrive/Laboratory/Alunos/Carlos'#local da pasta
caminhoo='/content/drive/MyDrive/Laboratory/Alunos/Carlos/download (1).csv'

# Parte 1

In [ ]:
#importação de bibliotecas
import re
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
def ordenandor_titulos(titulos_iniciais:list):
    lista_nomes_corretos=[]
    
    for titulo in titulos_iniciais:
        padrao = re.compile(r"[a-zA-Z]*[-]*[_]*[a-zA-Z]*_[0-9]{1,2}")
        resultado = padrao.findall(titulo)
        modificado = resultado[0]
        
        if len(modificado) == 14: 
            modificado = modificado.split("_")

            if len(modificado) == 2:
                modificado.insert(len(modificado)-1,"_0")
                modificado = "".join(modificado)
            
                
            elif len(modificado) == 3:
                modificado.insert(1,"_")
                modificado.insert(len(modificado)-1,"_0")
                modificado = "".join(modificado)
                
        lista_nomes_corretos.append(modificado)
    lista_nomes_corretos.sort()
    
    return lista_nomes_corretos

In [ ]:
def capta_tabelas(caminho:str):
    df=[]
    for num, pasta in enumerate(os.listdir(caminho)):
        df.append(pd.read_table(os.path.join(caminho, pasta)))   #lendo tabelas tabelas
        df[num].set_index('Geneid', inplace=True)  #tornando a colula Geneid o id das tabelas
    return df

In [ ]:
def junta_tabelas(lista_tabelas:list, lista_titulos:list):
    df_todos = pd.merge(lista_tabelas[0], lista_tabelas[1], on="Geneid")

    for itens in lista_tabelas[2:]:
        df_todos = pd.merge(df_todos, itens, on="Geneid")
        
    df_todos.columns = lista_titulos
    return df_todos

In [ ]:
def somas_reads(dataframe: list):
    somas=[[i for i in dataframe.sum()]]
    somas
    df_somas = pd.DataFrame(somas, columns=nomes)
    return df_somas/1000000

In [ ]:
#importação de bibliotecas
import re
import os
import pandas as pd

pd.set_option('display.max_columns', None)


id_genes=[8520, 2648, 8850, 10524, 7994, 23522, 11143, 84148, 9329, 1387, 79969, 2033, 3065, 3066, 8841, 9759, 10014, 10013, 51564, 55869, 9734, 83933, 23411, 22933, 23410, 23409, 23408, 51548, 51547]
df,renomear=[],[]#declaração de variaveis

renomear = ordenandor_titulos(os.listdir(dados))
nomes = [i for i in renomear]
nomes.sort()


df = capta_tabelas(dados)
#renomear
#df

In [ ]:
df_todos = junta_tabelas(df, renomear)
df_todos.head(3)

,Infected_Lbr_01,Infected_Lbr_02,Infected_Lbr_03,Infected_Lbr_04,Infected_Lbr_05,Infected_Lbr_06,Infected_Lbr_07,Infected_Lbr_08,Infected_Lbr_09,Infected_Lbr_10,Infected_Lbr_11,Infected_Lbr_12,Infected_Lbr_13,Infected_Lbr_14,Infected_Lbr_15,Infected_Lbr_16,Infected_Lbr_17,Infected_Lbr_18,Infected_Lbr_19,Infected_Lbr_20,Infected_Lbr_21,Infected_Lbr_22,Non-infected_01,Non-infected_02,Non-infected_03,Non-infected_04,Non-infected_05,Non-infected_06,Non-infected_07,Non-infected_08,Non-infected_09,Non-infected_10,Non-infected_11,Non-infected_12,Non-infected_13,Non-infected_14,Non-infected_15,Non-infected_16,Non-infected_17,Non-infected_18,Non-infected_19,Non-infected_20,Non-infected_21,Non-infected_22,Non-infected_23,Non-infected_24,Non-infected_25,Non-infected_26,Non-infected_27,Non-infected_28
Geneid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100287102,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,0
653635,4,1,6,4,2,6,4,11,6,0,8,6,2,2,3,3,3,12,9,9,15,5,5,1,15,13,13,1,1,0,1,7,5,12,8,6,8,7,3,16,11,7,10,16,15,13,14,30,11,12
102466751,0,2,0,2,1,0,0,0,0,0,1,1,0,0,2,2,4,2,6,0,2,1,1,1,2,4,4,1,1,0,2,3,5,6,2,3,4,5,5,7,6,5,4,4,4,5,7,7,1,6

In [ ]:
df_final= df_todos[nomes]
df_final.head(3)

,Infected_Lbr_01,Infected_Lbr_02,Infected_Lbr_03,Infected_Lbr_04,Infected_Lbr_05,Infected_Lbr_06,Infected_Lbr_07,Infected_Lbr_08,Infected_Lbr_09,Infected_Lbr_10,Infected_Lbr_11,Infected_Lbr_12,Infected_Lbr_13,Infected_Lbr_14,Infected_Lbr_15,Infected_Lbr_16,Infected_Lbr_17,Infected_Lbr_18,Infected_Lbr_19,Infected_Lbr_20,Infected_Lbr_21,Infected_Lbr_22,Non-infected_01,Non-infected_02,Non-infected_03,Non-infected_04,Non-infected_05,Non-infected_06,Non-infected_07,Non-infected_08,Non-infected_09,Non-infected_10,Non-infected_11,Non-infected_12,Non-infected_13,Non-infected_14,Non-infected_15,Non-infected_16,Non-infected_17,Non-infected_18,Non-infected_19,Non-infected_20,Non-infected_21,Non-infected_22,Non-infected_23,Non-infected_24,Non-infected_25,Non-infected_26,Non-infected_27,Non-infected_28
Geneid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100287102,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,0
653635,4,1,6,4,2,6,4,11,6,0,8,6,2,2,3,3,3,12,9,9,15,5,5,1,15,13,13,1,1,0,1,7,5,12,8,6,8,7,3,16,11,7,10,16,15,13,14,30,11,12
102466751,0,2,0,2,1,0,0,0,0,0,1,1,0,0,2,2,4,2,6,0,2,1,1,1,2,4,4,1,1,0,2,3,5,6,2,3,4,5,5,7,6,5,4,4,4,5,7,7,1,6

In [ ]:
df_exportar=df_final.loc[id_genes]
df_exportar.head()

,Infected_Lbr_01,Infected_Lbr_02,Infected_Lbr_03,Infected_Lbr_04,Infected_Lbr_05,Infected_Lbr_06,Infected_Lbr_07,Infected_Lbr_08,Infected_Lbr_09,Infected_Lbr_10,Infected_Lbr_11,Infected_Lbr_12,Infected_Lbr_13,Infected_Lbr_14,Infected_Lbr_15,Infected_Lbr_16,Infected_Lbr_17,Infected_Lbr_18,Infected_Lbr_19,Infected_Lbr_20,Infected_Lbr_21,Infected_Lbr_22,Non-infected_01,Non-infected_02,Non-infected_03,Non-infected_04,Non-infected_05,Non-infected_06,Non-infected_07,Non-infected_08,Non-infected_09,Non-infected_10,Non-infected_11,Non-infected_12,Non-infected_13,Non-infected_14,Non-infected_15,Non-infected_16,Non-infected_17,Non-infected_18,Non-infected_19,Non-infected_20,Non-infected_21,Non-infected_22,Non-infected_23,Non-infected_24,Non-infected_25,Non-infected_26,Non-infected_27,Non-infected_28
Geneid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8520,481,506,439,668,675,655,715,906,964,435,698,866,704,404,1106,947,1000,840,730,561,587,404,638,388,794,1277,1277,437,646,313,480,580,434,361,365,392,409,254,257,793,803,361,620,988,1030,1045,620,603,312,892
2648,142,163,93,102,79,100,86,58,65,71,99,142,80,78,189,92,99,215,177,108,115,84,107,67,200,370,370,113,139,77,144,102,94,181,158,193,137,139,149,276,308,175,311,218,224,258,287,267,115,253
8850,10312,11484,6216,8770,6210,8096,6752,6064,6460,9097,13409,18460,12616,3871,11665,16875,18356,6905,5900,3941,4241,8031,12063,8285,11130,9157,9157,7563,10897,4593,7134,12540,10034,11463,10764,7072,7200,3213,3247,7196,7505,4131,6358,20296,12777,13139,6337,6205,7543,21512
10524,236,237,271,318,268,269,316,372,418,235,220,443,188,242,640,346,386,438,369,331,323,291,414,202,487,589,589,256,334,153,244,331,260,193,150,208,238,179,209,342,398,196,261,578,387,433,378,342,139,343
7994,2778,3160,3456,5061,4319,4618,4613,4397,4819,2300,4879,4777,4622,2280,6524,3644,4031,6233,5358,3254,3462,2240,3554,2835,6200,7922,7922,3940,5723,2708,4248,4484,3229,3134,3037,3502,3726,2754,2878,5779,5965,3911,5992,6702,5882,5916,7173,6985,2422,6699

In [ ]:
df_exportar.to_csv('/content/drive/MyDrive/Laboratory/Alunos/Carlos/GSE162760.csv')

In [ ]:
pd.set_option('display.max_columns', None)


id_genes=[8520, 2648, 8850, 10524, 7994, 23522, 11143, 84148, 9329, 1387, 79969, 2033, 3065, 3066, 8841, 9759, 10014, 10013, 51564, 55869, 9734, 83933, 23411, 22933, 23410, 23409, 23408, 51548, 51547]


df_completo,df,renomear=[], [],[]#declaração de variaveis

renomear = ordenandor_titulos(os.listdir(dados))
nomes = [i for i in renomear]
nomes.sort()


for num, pasta in enumerate(os.listdir(dados)):
  df.append(pd.read_table(os.path.join(dados, pasta)))   #lendo tabelas tabelas
  df[num].set_index('Geneid', inplace=True)  #tornando a colula Geneid o id das tabelas

df_completo = pd.merge(df[0], df[1], on="Geneid")

for itens in df[2:]:
    df_completo = pd.merge(df_completo, itens, on="Geneid")
df_completo.columns = renomear

In [ ]:
os.listdir(tabela_final)
pd.set_option('display.max_columns', None, 'display.max_rows', None)


#variável para receber o id do arquivo google
arquivo_id="11HBWSzyuAeOHDfnpXKW1D8UEzwWVu3C4dTRKKWj87GY"


#variável para recer o id da planilhha
sheet_id="gviz/tq?tqx=out:csv&id=1570468428"


aaaa=pd.read_csv(f"https://docs.google.com/spreadsheets/d/{arquivo_id}/{sheet_id}")
colunas= [i for i in aaaa['Gene_id']]
#aaaa
#a=[i for i in range(0, len(aaaa.shape[0]))]
#colunas
print(aaaa["Gene_id"].to_list())

['HAT1/8520', 'KAT2A/2648', 'KAT2B/8850', 'KAT5/10524', 'KAT6A/7994', 'KAT6B/23522', 'KAT7/11143', 'KAT8/84148', 'KAT12/9329', 'CREBBP/1387', 'aTAT1/79969', 'p300/2033', 'HDAC1/3065', 'HDAC2/3066', 'HDAC3/8841', 'HDAC4/9759', 'HDAC5/10014', 'HDAC6/10013', 'HDAC7/51564', 'HDAC8/55869', 'HDAC9/9734', 'HDAC10/83933', 'SIRT1/23411', 'SIRT2/22933', 'SIRT3/23410', 'SIRT4/23409', 'SIRT5/23408', 'SIRT6/51548', 'SIRT7/51547']

In [ ]:
df_grafico= aaaa.T
df_grafico.columns= colunas
df_grafico.head(3)

,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
Gene_id,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
Infected_Lbr_01,-0.281492,-0.102532,2.449852,1.492359,1.535538,-2.393093,0.33091,1.457237,-1.066964,-0.757818,0.0,0.904209,1.416517,-0.323928,-0.20612,-2.500136,-1.127827,1.379376,-0.209944,-4.243825,-3.619578,-0.983626,1.006053,-0.887682,-1.866505,-2.758543,-0.349198,-1.532648,2.60943
Infected_Lbr_02,-0.369317,-0.190141,2.449041,1.617601,1.551514,-2.328699,0.347383,1.344006,-1.021679,-0.74716,0.0,0.900116,1.4886,-0.465837,-0.039364,-2.432815,-1.096663,1.365585,-0.322675,-4.544035,-3.647028,-1.334269,1.069773,-0.658725,-1.707049,-3.179576,-0.374229,-2.141866,2.541968

In [ ]:
lista_index = df_grafico.index.to_list()
lista_index=lista_index[:]
a = {"HAT1/8520":lista_index}
df_grafico.insert(0, "HAT1/8520", lista_index, True)
#df_grafico["HAT1/8520"]= lista_index
novo_index=[i for i in range(0, df_grafico.shape[0])]
df_grafico.insert(0, "novo_index", novo_index, True)
df_grafico.head(3)

,novo_index,HAT1/8520,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
Gene_id,0,Gene_id,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
Infected_Lbr_01,1,Infected_Lbr_01,-0.281492,-0.102532,2.449852,1.492359,1.535538,-2.393093,0.33091,1.457237,-1.066964,-0.757818,0.0,0.904209,1.416517,-0.323928,-0.20612,-2.500136,-1.127827,1.379376,-0.209944,-4.243825,-3.619578,-0.983626,1.006053,-0.887682,-1.866505,-2.758543,-0.349198,-1.532648,2.60943
Infected_Lbr_02,2,Infected_Lbr_02,-0.369317,-0.190141,2.449041,1.617601,1.551514,-2.328699,0.347383,1.344006,-1.021679,-0.74716,0.0,0.900116,1.4886,-0.465837,-0.039364,-2.432815,-1.096663,1.365585,-0.322675,-4.544035,-3.647028,-1.334269,1.069773,-0.658725,-1.707049,-3.179576,-0.374229,-2.141866,2.541968

In [ ]:
df_grafico.set_index('novo_index',inplace=True)

In [ ]:
df_grafico_final= df_grafico.drop([0])
df_grafico_final.head(3)

,HAT1/8520,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
novo_index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Infected_Lbr_01,-0.281492,-0.102532,2.449852,1.492359,1.535538,-2.393093,0.33091,1.457237,-1.066964,-0.757818,0.0,0.904209,1.416517,-0.323928,-0.20612,-2.500136,-1.127827,1.379376,-0.209944,-4.243825,-3.619578,-0.983626,1.006053,-0.887682,-1.866505,-2.758543,-0.349198,-1.532648,2.60943
2,Infected_Lbr_02,-0.369317,-0.190141,2.449041,1.617601,1.551514,-2.328699,0.347383,1.344006,-1.021679,-0.74716,0.0,0.900116,1.4886,-0.465837,-0.039364,-2.432815,-1.096663,1.365585,-0.322675,-4.544035,-3.647028,-1.334269,1.069773,-0.658725,-1.707049,-3.179576,-0.374229,-2.141866,2.541968
3,Infected_Lbr_03,-0.208227,-0.412735,2.097109,1.516858,1.46884,-2.200227,0.377812,1.080896,-1.018232,-0.423722,0.0,1.038624,1.359802,-0.037716,-0.046048,-2.419576,-1.563864,1.399911,-0.854007,-4.113841,-4.356587,-1.690718,0.937676,-1.03384,-1.727008,-3.313632,-0.238025,-2.750703,1.978037

In [ ]:
#sns.swarmplot(data=tips, x="day", y="total_bill")
lista_de_colunas = df_grafico_final.columns.to_list()
valores=[]
for i in lista_de_colunas:
  valores.append(df_grafico_final[i].values)
valores[0]

array([['Infected_Lbr_01', -0.2814921541],
       ['Infected_Lbr_02', -0.3693171562],
       ['Infected_Lbr_03', -0.2082267148],
       ['Infected_Lbr_04', -0.2567940102],
       ['Infected_Lbr_05', -0.01601866543],
       ['Infected_Lbr_06', -0.05258598364],
       ['Infected_Lbr_07', -0.06798115188],
       ['Infected_Lbr_08', 9.746372399],
       ['Infected_Lbr_09', -0.3717373049],
       ['Infected_Lbr_10', -0.3539373888],
       ['Infected_Lbr_11', -0.3077262461],
       ['Infected_Lbr_12', -0.3615677736],
       ['Infected_Lbr_13', -0.3721820856],
       ['Infected_Lbr_14', -0.3310066398],
       ['Infected_Lbr_15', -0.329725184],
       ['Infected_Lbr_16', -0.3920947017],
       ['Infected_Lbr_17', 2.974127776],
       ['Infected_Lbr_18', -0.4665926447],
       ['Infected_Lbr_19', 0.02460358573],
       ['Infected_Lbr_20', -0.008125606184],
       ['Infected_Lbr_21', -0.3170537896],
       ['Infected_Lbr_22', -0.3016526514],
       ['Non-infected_01', -0.4221439199],
       ['Non-infected_02', -0.4983335793],
       ['Non-infected_03', -0.4271521557],
       ['Non-infected_04', -0.4322241503],
       ['Non-infected_05', -0.2012629394],
       ['Non-infected_06', -0.2012629394],
       ['Non-infected_07', -0.447990019],
       ['Non-infected_08', -0.404087158],
       ['Non-infected_09', -0.4823074758],
       ['Non-infected_10', -0.5298244128],
       ['Non-infected_11', -0.6461526832],
       ['Non-infected_12', -0.4879773924],
       ['Non-infected_13', -0.8420169632],
       ['Non-infected_14', -0.7464193504],
       ['Non-infected_15', -0.7157884718],
       ['Non-infected_16', -0.7138233572],
       ['Non-infected_17', -0.7574989732],
       ['Non-infected_18', -0.8132803749],
       ['Non-infected_19', -0.2093989338],
       ['Non-infected_20', -0.2158548483],
       ['Non-infected_21', -0.6219563191],
       ['Non-infected_22', -0.4314359012],
       ['Non-infected_23', -0.2528269408],
       ['Non-infected_24', -0.2741118403],
       ['Non-infected_25', -0.645476058],
       ['Non-infected_26', -0.6281982826],
       ['Non-infected_27', 2.751197013],
       ['Non-infected_28', -0.5661996671]], dtype=object)

In [ ]:

arquivo_id2="11HBWSzyuAeOHDfnpXKW1D8UEzwWVu3C4dTRKKWj87GY"

sheet_id2="gviz/tq?tqx=out:csv&id=430683548"

arquivo_esperanca =pd.read_csv(f"https://docs.google.com/spreadsheets/d/{arquivo_id2}/{sheet_id2}")
arquivo_esperanca.set_index('Gene_id',inplace=True)
arquivo_esperanca.head(3)

,Infected_Lbr_01,Infected_Lbr_02,Infected_Lbr_03,Infected_Lbr_04,Infected_Lbr_05,Infected_Lbr_06,Infected_Lbr_07,Infected_Lbr_08,Infected_Lbr_09,Infected_Lbr_10,Infected_Lbr_11,Infected_Lbr_12,Infected_Lbr_13,Infected_Lbr_14,Infected_Lbr_15,Infected_Lbr_16,Infected_Lbr_17,Infected_Lbr_18,Infected_Lbr_19,Infected_Lbr_20,Infected_Lbr_21,Infected_Lbr_22,Non-infected_01,Non-infected_02,Non-infected_03,Non-infected_04,Non-infected_05,Non-infected_06,Non-infected_07,Non-infected_08,Non-infected_09,Non-infected_10,Non-infected_11,Non-infected_12,Non-infected_13,Non-infected_14,Non-infected_15,Non-infected_16,Non-infected_17,Non-infected_18,Non-infected_19,Non-infected_20,Non-infected_21,Non-infected_22,Non-infected_23,Non-infected_24,Non-infected_25,Non-infected_26,Non-infected_27,Non-infected_28
Gene_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
HAT1/8520,-0.281492,-0.369317,-0.208227,-0.256794,-0.016019,-0.052586,-0.067981,9.746372,-0.371737,-0.353937,-0.307726,-0.361568,-0.372182,-0.331007,-0.329725,-0.392095,2.974128,-0.466593,0.024604,-0.008126,-0.317054,-0.301653,-0.422144,-0.498334,-0.427152,-0.432224,-0.201263,-0.201263,-0.447990,-0.404087,-0.482307,-0.529824,-0.646153,-0.487977,-0.842017,-0.746419,-0.715788,-0.713823,-0.757499,-0.813280,-0.209399,-0.215855,-0.621956,-0.431436,-0.252827,-0.274112,-0.645476,-0.628198,2.751197,-0.566200
KAT2A/2648,-0.102532,-0.190141,-0.412735,-0.421874,-1.090950,-1.052653,-0.315030,9.819101,-0.096407,-0.071959,0.205759,0.177160,0.252379,-0.016497,0.026906,-0.009124,3.491773,-0.125031,-0.448600,-0.454098,0.607348,0.544655,0.708165,0.757856,0.224384,0.469092,0.902031,0.902031,0.491154,0.269918,0.384915,0.623665,0.037340,0.222295,1.052429,0.936064,1.152414,0.598707,1.263212,1.290718,1.158403,1.292130,1.223855,1.463665,0.436554,0.598283,1.133761,1.086938,4.201740,0.506349
KAT2B/8850,2.449852,2.449041,2.097109,2.086207,1.830370,1.795545,3.199256,13.113905,3.118268,3.163656,1.608464,1.595106,3.044672,3.013583,3.190349,3.145947,5.338108,2.035872,3.283684,3.293756,1.825828,1.816795,3.103701,3.109712,2.500243,2.480648,1.744555,1.744555,2.768965,2.775867,2.496596,2.467482,2.988607,2.976265,3.250527,3.239456,2.561106,2.527702,2.007223,1.949688,2.076105,2.112227,1.998165,2.030498,2.483707,2.481870,1.811685,1.838704,6.450419,3.129456

In [ ]:
arquivo_esperanca.T.head()
arquivo_esperancaT=arquivo_esperanca.T
arquivo_esperancaT.head(3)

Gene_id,HAT1/8520,KAT2A/2648,KAT2B/8850,KAT5/10524,KAT6A/7994,KAT6B/23522,KAT7/11143,KAT8/84148,KAT12/9329,CREBBP/1387,aTAT1/79969,p300/2033,HDAC1/3065,HDAC2/3066,HDAC3/8841,HDAC4/9759,HDAC5/10014,HDAC6/10013,HDAC7/51564,HDAC8/55869,HDAC9/9734,HDAC10/83933,SIRT1/23411,SIRT2/22933,SIRT3/23410,SIRT4/23409,SIRT5/23408,SIRT6/51548,SIRT7/51547
Infected_Lbr_01,-0.281492,-0.102532,2.449852,1.492359,1.535538,-2.393093,0.330910,1.457237,-1.066964,-0.757818,0.0,0.904209,1.416517,-0.323928,-0.206120,-2.500136,-1.127827,1.379376,-0.209944,-4.243825,-3.619578,-0.983626,1.006053,-0.887682,-1.866505,-2.758543,-0.349198,-1.532648,2.609430
Infected_Lbr_02,-0.369317,-0.190141,2.449041,1.617601,1.551514,-2.328699,0.347383,1.344006,-1.021679,-0.747160,0.0,0.900116,1.488600,-0.465837,-0.039364,-2.432815,-1.096663,1.365585,-0.322675,-4.544035,-3.647028,-1.334269,1.069773,-0.658725,-1.707049,-3.179576,-0.374229,-2.141866,2.541968
Infected_Lbr_03,-0.208227,-0.412735,2.097109,1.516858,1.468840,-2.200227,0.377812,1.080896,-1.018232,-0.423722,0.0,1.038624,1.359802,-0.037716,-0.046048,-2.419576,-1.563864,1.399911,-0.854007,-4.113841,-4.356587,-1.690718,0.937676,-1.033840,-1.727008,-3.313632,-0.238025,-2.750703,1.978037

In [ ]:
seaborn.objectslista=arquivo_esperancaT.index.to_list()
status=[]
for i in lista:
  if i.startswith('In'):
    status.append("Infected")
  if i.startswith('No'):
    status.append("Non-Infected")
#status.insert(0, "status")
status

NameError: ignored

In [ ]:
arquivo_esperancaT['status']=status
cols=arquivo_esperancaT.columns.to_list()
arquivo_esperancaT.head()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
#plt.figure(figsize=(10, 20))
#plt.yticks(range(-1, 5))
for i in cols:
  sns.catplot(data = arquivo_esperancaT, x="status", y=i, hue='status', size=10, jitter=True);
#arquivo_esperancaT.plot(x='status', y='HAT1/8520',figsize=(15,7), kind='scatter')

In [ ]:
sns.stripplot(data = arquivo_esperancaT, x="status", y='HAT1/8520', hue='status', size=5, dodge=False, jitter=False)

In [ ]:
bbb=arquivo_esperancaT.T

In [ ]:
arquivo_esperancaT[cols[:-1]].head()

In [ ]:
import pandas as pd
c = [['x', '1.23', '14.2'], 
     ['y', '20', '0.11'],
     ['z', '3', '10']]
df = pd.DataFrame(
    c, 
    columns=['first', 'second', 'third'])

df[['second', 'third']] = df[['second', 'third']].astype(float)

len(status)

# graficos

In [ ]:
#importação de bibliotecas
import re
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

caminho_imagens = "/content/drive/MyDrive/Carlos/imagens"
tabela_completa =pd.read_csv('/content/drive/MyDrive/Laboratory/Alunos/Carlos/arquivos/download (1).csv')
colunas2=tabela_completa.columns.to_list()
colunas2=colunas2[1:]
tabela_completa.set_index("Gene_id", inplace=True)
df_graficos = tabela_completa.T
estado = []

for i in colunas2:
  if i.startswith("Inf"):
    estado.append("Infected")
  elif i.startswith("Non"):
    estado.append("Non-Infected")

df_graficos["estado"] = estado
colunas3 = df_graficos.columns.to_list()
df_graficos.iloc[7:8]

kat  = [i for i in colunas3 if i.startswith("KAT")]
hdac = [i for i in colunas3 if i.startswith("HDA")]
sirt = [i for i in colunas3 if i.startswith("SIR")]

display(df_graficos.loc[['Infected_Lbr_08'],kat],
        df_graficos.loc[['Infected_Lbr_08'],hdac],
        df_graficos.loc[['Infected_Lbr_08'],sirt])

In [ ]:
tabela_altlier = df_graficos.drop(['Infected_Lbr_08'])
tabela_altlier.head()

In [ ]:
kat  = [i for i in colunas3 if i.startswith("KAT")]
hdac = [i for i in colunas3 if i.startswith("HDA")]
sirt = [i for i in colunas3 if i.startswith("SIR")]
nova_lista=[i.replace("/","-") for i in colunas3 ]#'HAT1-8520','KAT2A-2648'....

In [ ]:
# caminho_imagens = "/content/drive/MyDrive/Carlos/imagens"
# armazem=[]

# for col, lis in zip(colunas3, nova_lista):
#   grafico = sns.catplot(data = df_graficos, x="estado", y=col, size=5, jitter = True, hue='estado');

#   if col == "estado": continue

#   grafico = plt.title(col, fontsize=15, weight= 'bold');
#   grafico = plt.xlabel('status', fontdict={'size': 13});
#   grafico = plt.ylabel('Log²RPKM', fontdict={'size': 13})
  
  #grafico.savefig((f'{caminho_imagens}/{lis}.tif'), dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
  #plt.savefig((f'{caminho_imagens}/{lis}.png'), dpi=600, format='png', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
  #plt.show(grafico);
  #print("carregando")

In [ ]:
# for col, lis in zip(colunas3, nova_lista):
#   if col == "estado": continue
#   grafico1 = sns.catplot(data = df_graficos, y=col, x= 'estado', kind = "box");
#   grafico1 = plt.title(col, fontsize=15, weight= 'bold');
#   grafico1 = plt.xlabel('status', fontdict={'size': 13});
#   grafico1 = plt.ylabel('Log²RPKM', fontdict={'size': 13});
#   plt.show(grafico1);

In [ ]:
# for col, lis in zip(colunas3, nova_lista):
#   if col == "estado": continue
#   grafico = sns.catplot(data = df_graficos, y=col, x= 'estado',kind="violin", bw=.25, cut=0, split=True, inner="stick")
#   grafico = plt.title(col, fontsize=15, weight= 'bold');
#   grafico = plt.xlabel('status', fontdict={'size': 13});
#   grafico = plt.ylabel('Log²RPKM', fontdict={'size': 13});
#   plt.show(grafico);

In [ ]:

# for col, lis in zip(colunas3, nova_lista):
#   if col == "estado": continue
#   sns.catplot(data = df_graficos, y=col, x= 'estado', kind="violin",bw=.40, color=".9", inner=None)
#   sns.swarmplot(data = df_graficos, y=col, x= 'estado', size=5)

#   grafico = plt.title(col, fontsize=15, weight= 'bold');
#   grafico = plt.xlabel('status', fontdict={'size': 13});
#   grafico = plt.ylabel('Log²RPKM', fontdict={'size': 13});
#   plt.show(grafico);

In [ ]:
# for col, lis in zip(colunas3, nova_lista):
#   if col == "estado": continue
#   grafico = sns.swarmplot(data = df_graficos, x="estado", y=col , size=6);
#   grafico = plt.title(col, fontsize=15, weight= 'bold');
#   grafico = plt.xlabel('status', fontdict={'size': 13});
#   grafico = plt.ylabel('Log²RPKM', fontdict={'size': 13});
#   plt.show(grafico);

In [ ]:
# sns.catplot(data = df_graficos, x="estado", y="KAT2B/8850" , size=6);

In [ ]:
# for col, lis in zip(colunas3, nova_lista):
#   if col == "estado": continue
#   grafico1 = sns.stripplot(data = df_graficos, x="estado", palette="dark:#5A9_r",y=col , size=6, dodge=False);
#   grafico1 = plt.title(col, fontsize=15, weight= 'bold');
#   grafico1 = plt.xlabel('status', fontdict={'size': 13});
#   grafico1 = plt.ylabel('Log²RPKM', fontdict={'size': 13});
#   plt.show(grafico1);

In [ ]:
# aaaaa=sns.stripplot(data = df_graficos, x="estado", y="KAT2B/8850" , size=6, dodge=False);
# aaaaa=plt.title(u"GNAT", fontsize=15)
# plt.xlabel('Day of Week', fontdict={'size': 15})
# plt.ylabel('Tip Amount', fontdict={'size': 15})
# #plt.savefig(, dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')

In [ ]:
# xxx= sns.stripplot(data = df_graficos, x="estado", y="KAT2B/8850", size=6, dodge=True);

In [ ]:
''' import matplotlib.pyplot as plt

xmax = 9
ymax = 5

dados = {
    'PS3' : 2.0,
    'X360': 1.75,
    'PC'  : 1.70,
    'Wii' : 0.75,
    'PSV' : 1.60,
    '3DS' : 0.25,
    'DS'  : 0.33,
    'WiiU': 0.25
} '''

# Configura os eixos
#eixos = plt.gca()
# eixos.set_xlim([-0.5, xmax + 0.5])seaborn.objects
# eixos.set_ylim([0, ymax])

''' plt.scatter(*zip(*df_graficos["KAT2B/8850"].items()))
plt.show() '''

In [ ]:
from seaborn.utils import ci
sns.set_style("whitegrid")


# for i in kat:
  
#   plt.figure(figsize=(8,8))
#   graficos = sns.swarmplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i, size=5, dodge=True);
#   graficos = sns.boxplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i,
#                          showcaps=True,boxprops={'facecolor':'None'},
#                          showfliers=True,whiskerprops={'linewidth':1})
  
  
#   graficos.set_ylim([-4, 13.5])
#   nome_grafico=i.replace("/","-")


#   graficos = plt.title(i, fontsize=15, weight= 'bold');
#   graficos = plt.xlabel('status', fontdict={'size': 13});
#   graficos = plt.ylabel('Log²RPKM', fontdict={'size': 13});

#   #plt.savefig((f'{caminho_imagens}/KAT/{nome_grafico}.tif'), dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
#   plt.show(graficos);
#   print("carregando")

In [ ]:
from seaborn.utils import ci
sns.set_style("whitegrid")


for i in kat:
  
  plt.figure(figsize=(8,8))
  graficos = sns.swarmplot(data = tabela_altlier.sort_values("estado", ascending=False), x="estado", y=i, size=5, dodge=True);
  graficos = sns.boxplot(
                         data = tabela_altlier.sort_values("estado", ascending=False), 
                         x="estado", y=i, showcaps=True,
                         boxprops={'facecolor':'None'},
                         showfliers=True,whiskerprops={'linewidth':1}
                         )
  
  graficos.set_ylim([-3, 7])
  nome_grafico=i.replace("/","-")


  graficos = plt.title(i, fontsize=15, weight= 'bold');
  graficos = plt.xlabel('status', fontdict={'size': 13});
  graficos = plt.ylabel('Log²RPKM', fontdict={'size': 13});

  #plt.savefig((f'{caminho_imagens}/KAT/{nome_grafico}.tif'), dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
  plt.show(graficos);
  print("carregando")

In [ ]:
from seaborn.utils import ci
sns.set_style("whitegrid")


for i in hdac:
  
  plt.figure(figsize=(8,8))
  graficos = sns.swarmplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i, size=5, dodge=True);
  graficos = sns.boxplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i,
                         showcaps=True,boxprops={'facecolor':'None'},
                         showfliers=True,whiskerprops={'linewidth':1})
  #graficos.set_xlim([-0.5, 2 + 0.5])
  graficos.set_ylim([-2, 6])
  nome_grafico=i.replace("/","-")

  graficos = plt.title(i, fontsize=15, weight= 'bold');
  graficos = plt.xlabel('status', fontdict={'size': 13});
  graficos = plt.ylabel('Log²RPKM', fontdict={'size': 13});

  #plt.savefig((f'{caminho_imagens}/HDAC/{nome_grafico}.tif'), dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
  plt.show(graficos)
  print("")

In [ ]:
from seaborn.utils import ci
sns.set_style("whitegrid")


for i in sirt:
  
  plt.figure(figsize=(8,8))
  graficos = sns.swarmplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i, size=5, dodge=True);
  graficos = sns.boxplot(data = df_graficos.sort_values("estado", ascending=False), x="estado", y=i,
                         showcaps=True,boxprops={'facecolor':'None'},
                         showfliers=True,whiskerprops={'linewidth':1})
  #graficos.set_xlim([-0.5, 2 + 0.5])
  graficos.set_ylim([-6, 12])
  nome_grafico=i.replace("/","-")

  graficos = plt.title(i, fontsize=15, weight= 'bold');
  graficos = plt.xlabel('status', fontdict={'size': 13});
  graficos = plt.ylabel('Log²RPKM', fontdict={'size': 13});

  plt.savefig((f'{caminho_imagens}/SIRT/{nome_grafico}.tif'), dpi=600, format='tif', bbox_inches='tight', pad_inches=0.2, bbox=None, pad=None, dashes=None, loc='upper left', rot=0, vmax='I', vmin='I', hmax='I', hmin='I')
  plt.show(graficos)
  print("")

In [ ]:
df_graficos.sort_values("estado", ascending=False).head(1)

In [ ]:
# sns.get_dataset_names()
# teste = sns.load_dataset('tips')
!python --version

In [ ]:
!pip3 install seaborn --upgrade
#!pip install matplotlib --upgrade
#!pip install numpy --upgrade

In [ ]:
!pip3 install seaborn==0.12.0
!pip install seaborn==0.12.0
import seaborn as sns
#import seaborn.objects as so

 
sns.__version__

#sns.get_dataset_names()

In [ ]:
!apt-get -qq install -y seaborn==0.12.0

import seaborn as sns